#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import math
import os
import random
import re
import shutil
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

KB_EV_PER_K = 8.617333262145e-5
MONITOR_KEYS = ('FFSampling', 'PathSampling', 'MetaD', 'GASMD')


def parse_scalar(text: str) -> Any:
    value = text.strip()
    if not value:
        return None
    low = value.lower()
    if low in ('null', 'none', '~'):
        return None
    if low in ('true', 'yes', 'on'):
        return True
    if low in ('false', 'no', 'off'):
        return False
    if value.startswith('[') and value.endswith(']'):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [parse_scalar(part.strip()) for part in inner.split(',')]
    try:
        if any(mark in value for mark in ('.', 'e', 'E')):
            return float(value)
        return int(value)
    except ValueError:
        return value.strip('\'')


def load_yaml(path: Path) -> dict[str, Any]:
    try:
        import yaml  # type: ignore
    except Exception:
        yaml = None
    if yaml is not None:
        with path.open('r', encoding='utf-8') as handle:
            data = yaml.safe_load(handle)
        return data or {}

    root: dict[str, Any] = {}
    stack: list[tuple[int, dict[str, Any]]] = [(-1, root)]
    for raw in path.read_text(encoding='utf-8').splitlines():
        if not raw.strip() or raw.lstrip().startswith('#'):
            continue
        line = raw.split('#', 1)[0].rstrip()
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip(' '))
        key, sep, value = line.strip().partition(':')
        if not sep:
            raise ValueError(f'Cannot parse yaml line: {raw}')
        while stack and indent <= stack[-1][0]:
            stack.pop()
        parent = stack[-1][1]
        if value.strip() == '':
            child: dict[str, Any] = {}
            parent[key] = child
            stack.append((indent, child))
        else:
            parent[key] = parse_scalar(value)
    return root


def as_path(base: Path, value: str | Path) -> Path:
    path = Path(value)
    return path if path.is_absolute() else base / path


def require_file(path: Path, label: str) -> Path:
    if not path.exists():
        raise FileNotFoundError(f'{label} does not exist: {path}')
    return path


def read_key_value_cfg(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    for raw in path.read_text(encoding='utf-8').splitlines():
        line = raw.split('#', 1)[0].strip()
        if not line or ':' not in line:
            continue
        key, value = line.split(':', 1)
        data[key.strip()] = value.strip()
    return data


def write_gas_cfg(base_cfg: Path, output: Path, overrides: dict[str, Any]) -> None:
    text = base_cfg.read_text(encoding='utf-8').rstrip() + '\n'
    text += '\n# FFS runtime overrides generated by FFS_src/ffs_driver.py\n'
    for key, value in overrides.items():
        if isinstance(value, bool):
            rendered = 'true' if value else 'false'
        else:
            rendered = str(value)
        text += f'{key}: {rendered}\n'
    output.write_text(text, encoding='utf-8')



def format_temperature(value: float) -> str:
    return str(int(value)) if float(value).is_integer() else f'{value:g}'

def is_float_token(value: str) -> bool:
    try:
        float(value)
        return True
    except ValueError:
        return False

def rewrite_temperature_line(raw: str, temperature_K: float | None, velocity_seed: int | None) -> str:
    if temperature_K is None and velocity_seed is None:
        return raw
    prefix = raw[:len(raw) - len(raw.lstrip())]
    body = raw.strip()
    if not body or body.startswith('#'):
        return raw
    command, sep, comment = body.partition('#')
    parts = command.split()
    if not parts:
        return raw
    temperature = format_temperature(temperature_K) if temperature_K is not None else None
    changed = False
    if parts[0] == 'velocity' and len(parts) >= 2:
        if temperature is not None:
            parts[1] = temperature
            changed = True
        if velocity_seed is not None:
            if len(parts) >= 4 and parts[2] == 'seed':
                parts[3] = str(velocity_seed)
            elif len(parts) == 2:
                parts.extend(['seed', str(velocity_seed)])
            else:
                return raw
            changed = True
    elif parts[0] == 'ensemble':
        if temperature is None:
            return raw
        if 'temp' in parts:
            idx = parts.index('temp')
            if idx + 2 < len(parts):
                parts[idx + 1] = temperature
                parts[idx + 2] = temperature
                changed = True
        elif len(parts) >= 4 and parts[1].startswith(('nvt', 'npt')) and is_float_token(parts[2]) and is_float_token(parts[3]):
            parts[2] = temperature
            parts[3] = temperature
            changed = True
        else:
            return raw
    else:
        return raw
    if not changed:
        return raw
    rewritten = prefix + ' '.join(parts)
    if sep:
        rewritten += ' #' + comment
    return rewritten

def render_run_in(
    template: Path,
    output: Path,
    monitor_model: str,
    monitor_cfg: str,
    max_steps: int,
    temperature_K: float | None,
    velocity_seed: int | None,
) -> None:
    lines: list[str] = []
    monitor_line = f'FFSampling {monitor_model} {monitor_cfg}'
    run_line = f'run {max_steps}'
    inserted_monitor = False
    inserted_run = False
    for raw in template.read_text(encoding='utf-8').splitlines():
        stripped = raw.strip()
        if not stripped:
            lines.append(raw)
            continue
        raw = rewrite_temperature_line(raw, temperature_K, velocity_seed)
        stripped = raw.strip()
        key = stripped.split()[0]
        if key in MONITOR_KEYS:
            continue
        if key == 'run':
            if not inserted_monitor:
                lines.append(monitor_line)
                inserted_monitor = True
            if not inserted_run:
                lines.append(run_line)
                inserted_run = True
            continue
        lines.append(raw)
    if not inserted_monitor:
        lines.append(monitor_line)
    if not inserted_run:
        lines.append(run_line)
    output.write_text('\n'.join(lines).rstrip() + '\n', encoding='utf-8')



def strip_extxyz_velocities(source: Path, target: Path) -> bool:
    lines = source.read_text(encoding='utf-8', errors='replace').splitlines()
    if len(lines) < 2:
        return False
    comment = lines[1]
    match = re.search(r'Properties=(["\'])(.*?)\1', comment)
    quoted = True
    if match:
        quote = match.group(1)
        spec = match.group(2)
    else:
        match = re.search(r'Properties=([^\s]+)', comment)
        if not match:
            return False
        quoted = False
        quote = ''
        spec = match.group(1)
    tokens = spec.split(':')
    if len(tokens) % 3 != 0:
        return False

    keep_indices: list[int] = []
    kept_properties: list[str] = []
    offset = 0
    removed = False
    for i in range(0, len(tokens), 3):
        name, value_type, count_text = tokens[i:i + 3]
        try:
            count = int(count_text)
        except ValueError:
            return False
        indices = list(range(offset, offset + count))
        offset += count
        if name.lower() in ('vel', 'velocity'):
            removed = True
            continue
        kept_properties.extend([name, value_type, count_text])
        keep_indices.extend(indices)
    if not removed:
        return False

    atom_lines: list[str] = []
    for raw in lines[2:]:
        parts = raw.split()
        if len(parts) < offset:
            return False
        atom_lines.append(' '.join(parts[i] for i in keep_indices))

    new_spec = ':'.join(kept_properties)
    if quoted:
        replacement = f'Properties={quote}{new_spec}{quote}'
    else:
        replacement = f'Properties={new_spec}'
    new_comment = comment[:match.start()] + replacement + comment[match.end():]
    target.write_text('\n'.join([lines[0], new_comment] + atom_lines) + '\n', encoding='utf-8')
    return True


def copy_start_model(source: Path, target: Path, resample_velocities: bool) -> bool:
    if resample_velocities and strip_extxyz_velocities(source, target):
        return True
    shutil.copy2(source, target)
    return False

def copy_inputs(files: list[Path], workdir: Path) -> None:
    for item in files:
        target = workdir / item.name
        if item.is_dir():
            if target.exists():
                shutil.rmtree(target)
            shutil.copytree(item, target)
        else:
            shutil.copy2(item, target)


def read_last_cv_log(path: Path) -> tuple[int, list[float], int]:
    if not path.exists():
        return 0, [], 0
    rows: list[list[float]] = []
    for raw in path.read_text(encoding='utf-8', errors='replace').splitlines():
        parts = raw.split()
        if not parts:
            continue
        try:
            rows.append([float(part) for part in parts])
        except ValueError:
            continue
    if not rows:
        return 0, [], 0
    last = rows[-1]
    status = int(round(last[0])) if last else 0
    return status, last[1:], len(rows)


def estimate_steps(cv_rows: int, cv_log_interval: int) -> int:
    if cv_rows <= 0:
        return 0
    return max(1, cv_rows - 1) * max(1, cv_log_interval)


def parse_completed_steps(stdout: str) -> int:
    matches = re.findall(r'(\d+)\s+steps completed\.', stdout)
    return int(matches[-1]) if matches else 0


def safe_name(prefix: str, index: int) -> str:
    return f'{prefix}_{index:06d}'


def read_template_run_steps(template: Path, default: int = 10000) -> int:
    for raw in template.read_text(encoding='utf-8').splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith('#'):
            continue
        parts = stripped.split()
        if parts and parts[0] == 'run' and len(parts) > 1:
            try:
                return int(parts[1])
            except ValueError:
                break
    return default


def normalize_interface_steps(value: Any, count: int, default: int) -> list[int]:
    if value is None:
        return [default for _ in range(count)]
    if isinstance(value, list):
        steps = [int(item) for item in value]
        if len(steps) == 1:
            return steps * count
        if len(steps) != count:
            raise ValueError('ffs.interface_max_steps must be an integer or have len(interfaces)-1 entries')
        return steps
    return [int(value) for _ in range(count)]


@dataclass
class RunResult:
    stage: str
    index: int
    status: int
    cv: list[float]
    cv_rows: int
    steps_estimate: int
    max_steps: int
    velocity_seed: int | None
    resampled_velocities: bool
    wall_seconds: float
    return_code: int
    workdir: Path
    kept: bool


@dataclass
class FFSConfig:
    root: Path
    executable: Path
    base_model: Path
    initial_models: list[Path]
    run_template: Path
    gas_model: Path
    gas_config: Path
    work_dir: Path
    overwrite_work_dir: bool
    resume: bool
    state_file_name: str
    extra_files: list[Path]
    cuda_visible_devices: str | None
    interfaces: list[float]
    direction: int
    cv_index: int
    replicas_per_crossing: int
    flux_min_crossings: int
    flux_max_runs: int
    min_trials_per_interface: int
    max_trials_per_interface: int
    min_successes_per_interface: int
    max_successes_per_interface: int
    keep_failed: bool
    random_seed: int | None
    timestep_fs: float
    temperature_K: float | None
    resample_velocities: bool
    fail_interface: float
    cv_log_interval: int
    flux_max_steps: int
    interface_max_steps: list[int]
    adaptive_enabled: bool
    adaptive_min_interval_width: float
    adaptive_max_refinements: int
    adaptive_strategy: str
    recovery_mode: str
    recovery_max_rounds_per_interface: int
    recovery_refill_successes: int
    recovery_refill_max_trials: int
    command_prefix: list[str] = field(default_factory=list)

    @classmethod
    def from_yaml(cls, path: Path) -> FFSConfig:
        cfg = load_yaml(path)
        root = path.parent.resolve()
        run_cfg = cfg.get('run', {})
        ffs_cfg = cfg.get('ffs', {})
        md_cfg = cfg.get('md', {})
        adaptive_cfg = cfg.get('adaptive', ffs_cfg.get('adaptive', {})) or {}
        recovery_cfg = cfg.get('recovery', ffs_cfg.get('recovery', {})) or {}

        executable = require_file(as_path(root, run_cfg.get('executable', 'src/build/gpu-sampling')), 'gpu-sampling executable')
        base_model = require_file(as_path(root, run_cfg.get('base_model', 'model.xyz')), 'base model')
        initial_model_values = run_cfg.get('initial_models', [])
        if isinstance(initial_model_values, str):
            initial_model_values = [initial_model_values]
        initial_models = [require_file(as_path(root, item), 'initial model') for item in initial_model_values]
        if not initial_models:
            initial_models = [base_model]
        run_template = require_file(as_path(root, run_cfg.get('run_template', 'run.in')), 'run template')
        gas_model = require_file(as_path(root, run_cfg.get('gas_model', 'GASCVModel.pt')), 'GAS model')
        gas_config = require_file(as_path(root, run_cfg.get('gas_config', 'GAScfg.yaml')), 'GAS config')
        work_dir = as_path(root, run_cfg.get('work_dir', 'FFS_runs')).resolve()
        extra_files = [require_file(as_path(root, item), 'extra file') for item in run_cfg.get('extra_files', [])]
        interfaces = [float(item) for item in ffs_cfg.get('interfaces', [])]
        if len(interfaces) < 2:
            raise ValueError('ffs.interfaces must contain at least two interface values')
        direction = int(ffs_cfg.get('direction', 1))
        direction = 1 if direction >= 0 else -1
        default_fail = interfaces[0]
        gas_values = read_key_value_cfg(gas_config)
        cv_log_interval = int(md_cfg.get('cv_log_interval', gas_values.get('cv_log_interval', 1)))
        template_run_steps = read_template_run_steps(run_template)
        flux_max_steps = int(ffs_cfg.get('flux_max_steps', template_run_steps))
        interface_max_steps = normalize_interface_steps(
            ffs_cfg.get('interface_max_steps'),
            len(interfaces) - 1,
            template_run_steps,
        )
        prefix = run_cfg.get('command_prefix', [])
        if isinstance(prefix, str):
            prefix = prefix.split()
        resample_velocities = bool(md_cfg.get('resample_velocities', True))
        replicas_per_crossing = int(ffs_cfg.get('replicas_per_crossing', 1))
        if not resample_velocities:
            replicas_per_crossing = 1
        return cls(
            root=root,
            executable=executable.resolve(),
            base_model=base_model.resolve(),
            initial_models=[item.resolve() for item in initial_models],
            run_template=run_template.resolve(),
            gas_model=gas_model.resolve(),
            gas_config=gas_config.resolve(),
            work_dir=work_dir,
            overwrite_work_dir=bool(run_cfg.get('overwrite_work_dir', False)),
            resume=bool(run_cfg.get('resume', False)),
            state_file_name=str(run_cfg.get('state_file', 'driver_state.json')),
            extra_files=extra_files,
            cuda_visible_devices=run_cfg.get('cuda_visible_devices'),
            interfaces=interfaces,
            direction=direction,
            cv_index=int(ffs_cfg.get('cv_index', 0)),
            replicas_per_crossing=replicas_per_crossing,
            flux_min_crossings=int(ffs_cfg.get('flux_min_crossings', 20)),
            flux_max_runs=int(ffs_cfg.get('flux_max_runs', 200)),
            min_trials_per_interface=int(ffs_cfg.get('min_trials_per_interface', 20)),
            max_trials_per_interface=int(ffs_cfg.get('max_trials_per_interface', 200)),
            min_successes_per_interface=int(ffs_cfg.get('min_successes_per_interface', 10)),
            max_successes_per_interface=int(ffs_cfg.get('max_successes_per_interface', 1000000000)),
            keep_failed=bool(ffs_cfg.get('keep_failed', False)),
            random_seed=ffs_cfg.get('random_seed'),
            timestep_fs=float(md_cfg.get('timestep_fs', 1.0)),
            temperature_K=None if md_cfg.get('temperature_K') is None else float(md_cfg.get('temperature_K')),
            resample_velocities=resample_velocities,
            fail_interface=float(ffs_cfg.get('fail_interface', default_fail)),
            cv_log_interval=cv_log_interval,
            flux_max_steps=flux_max_steps,
            interface_max_steps=interface_max_steps,
            adaptive_enabled=bool(adaptive_cfg.get('enabled', False)),
            adaptive_min_interval_width=float(adaptive_cfg.get('min_interval_width', 0.0)),
            adaptive_max_refinements=int(adaptive_cfg.get('max_refinements', 0)),
            adaptive_strategy=str(adaptive_cfg.get('strategy', 'midpoint')),
            recovery_mode=str(recovery_cfg.get('mode', 'stop')),
            recovery_max_rounds_per_interface=int(recovery_cfg.get('max_rounds_per_interface', 0)),
            recovery_refill_successes=int(recovery_cfg.get('refill_successes', ffs_cfg.get('min_successes_per_interface', 10))),
            recovery_refill_max_trials=int(recovery_cfg.get('refill_max_trials', ffs_cfg.get('max_trials_per_interface', 200))),
            command_prefix=list(prefix),
        )


class FFSDriver:
    def __init__(self, config: FFSConfig, dry_run: bool = False) -> None:
        self.config = config
        self.dry_run = dry_run
        self.results: list[RunResult] = []
        self.events_path = config.work_dir / 'events.jsonl'
        self.states_dir = config.work_dir / 'states'
        self.segments_dir = config.work_dir / 'success_segments'
        self.trials_dir = config.work_dir / 'trials'
        self.state_path = config.work_dir / config.state_file_name
        self.adaptive_refinements: list[dict[str, Any]] = []
        self.stage_launch_counts: dict[str, int] = {}
        self.initial_model_cursor = 0
        self.resume_phase: str | None = None
        if config.recovery_mode not in ('stop', 'previous_interface', 'initial_state'):
            raise ValueError(f'unsupported recovery.mode: {config.recovery_mode}')
        if config.random_seed is not None:
            random.seed(config.random_seed)

    def prepare(self) -> None:
        managed = [
            self.events_path,
            self.config.work_dir / 'summary.json',
            self.config.work_dir / 'interfaces.csv',
            self.state_path,
            self.states_dir,
            self.segments_dir,
            self.trials_dir,
        ]
        existing = [path for path in managed if path.exists()]
        if self.config.resume:
            if not self.state_path.exists():
                raise RuntimeError(f'run.resume is true but state file does not exist: {self.state_path}')
            self.config.work_dir.mkdir(parents=True, exist_ok=True)
            self.states_dir.mkdir(parents=True, exist_ok=True)
            self.segments_dir.mkdir(parents=True, exist_ok=True)
            self.trials_dir.mkdir(parents=True, exist_ok=True)
            return
        if existing:
            if not self.config.overwrite_work_dir:
                joined = ', '.join(str(path) for path in existing[:4])
                raise RuntimeError(
                    'work_dir already contains FFS outputs; set run.overwrite_work_dir: true, '
                    'set run.resume: true, or choose a new work_dir. '
                    f'Existing: {joined}'
                )
            for path in existing:
                if path.is_dir():
                    shutil.rmtree(path)
                else:
                    path.unlink()
        self.config.work_dir.mkdir(parents=True, exist_ok=True)
        self.states_dir.mkdir(parents=True, exist_ok=True)
        self.segments_dir.mkdir(parents=True, exist_ok=True)
        self.trials_dir.mkdir(parents=True, exist_ok=True)
        self.events_path.write_text('', encoding='utf-8')

    def state_dir(self, interface_index: int) -> Path:
        path = self.states_dir / f'interface_{interface_index:03d}'
        path.mkdir(parents=True, exist_ok=True)
        return path

    def segment_dir(self, interface_index: int) -> Path:
        path = self.segments_dir / f'interface_{interface_index:03d}'
        path.mkdir(parents=True, exist_ok=True)
        return path

    def build_trial_dir(self, stage: str, index: int) -> Path:
        launch_index = self.stage_launch_counts.get(stage, 0) + 1
        self.stage_launch_counts[stage] = launch_index
        path = self.trials_dir / stage / safe_name('run', launch_index)
        if path.exists():
            shutil.rmtree(path)
        path.mkdir(parents=True)
        return path

    def next_velocity_seed(self) -> int | None:
        if self.config.random_seed is None:
            return None
        return random.randint(1, 2147483647)

    def next_initial_model(self) -> Path:
        model = self.config.initial_models[self.initial_model_cursor % len(self.config.initial_models)]
        self.initial_model_cursor += 1
        return model

    def launch(self, stage: str, index: int, start_model: Path, target: float, stop_on_fail: bool, max_steps: int) -> RunResult:
        workdir = self.build_trial_dir(stage, index)
        velocity_seed = self.next_velocity_seed()
        resampled_velocities = copy_start_model(start_model, workdir / 'model.xyz', self.config.resample_velocities)
        shutil.copy2(self.config.gas_model, workdir / self.config.gas_model.name)
        copy_inputs([self.config.gas_config] + self.config.extra_files, workdir)
        runtime_cfg_name = 'GAScfg.ffs.yaml'
        write_gas_cfg(
            self.config.gas_config,
            workdir / runtime_cfg_name,
            {
                'ffs_enabled': True,
                'ffs_stop_on_fail': stop_on_fail,
                'ffs_cv_index': self.config.cv_index,
                'ffs_direction': self.config.direction,
                'ffs_target_interface': target,
                'ffs_fail_interface': self.config.fail_interface,
            },
        )
        render_run_in(
            self.config.run_template,
            workdir / 'run.in',
            self.config.gas_model.name,
            runtime_cfg_name,
            max_steps,
            self.config.temperature_K,
            velocity_seed,
        )
        command = self.config.command_prefix + [str(self.config.executable), '-m', 'model.xyz', '-i', 'run.in']
        env = os.environ.copy()
        if self.config.cuda_visible_devices is not None:
            env['CUDA_VISIBLE_DEVICES'] = str(self.config.cuda_visible_devices)
        if self.dry_run:
            return RunResult(stage, index, 0, [], 0, 0, max_steps, velocity_seed, resampled_velocities, 0.0, 0, workdir, True)
        start = time.time()
        completed = subprocess.run(command, cwd=workdir, env=env, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        wall = time.time() - start
        (workdir / 'gpu_sampling.out').write_text(completed.stdout or '', encoding='utf-8')
        status, cv, cv_rows = read_last_cv_log(workdir / 'GASCVlog.txt')
        result = RunResult(
            stage=stage,
            index=index,
            status=status,
            cv=cv,
            cv_rows=cv_rows,
            steps_estimate=parse_completed_steps(completed.stdout or '') or estimate_steps(cv_rows, self.config.cv_log_interval),
            max_steps=max_steps,
            velocity_seed=velocity_seed,
            resampled_velocities=resampled_velocities,
            wall_seconds=wall,
            return_code=completed.returncode,
            workdir=workdir,
            kept=True,
        )
        return result

    def record_json_event(self, payload: dict[str, Any]) -> None:
        with self.events_path.open('a', encoding='utf-8') as handle:
            handle.write(json.dumps(payload, ensure_ascii=False) + '\n')

    def count_event_lines(self) -> int:
        if not self.events_path.exists():
            return 0
        with self.events_path.open('r', encoding='utf-8') as handle:
            return sum(1 for line in handle if line.strip())

    def read_event_lines_after(self, cursor: int) -> list[dict[str, Any]]:
        if not self.events_path.exists():
            return []
        events: list[dict[str, Any]] = []
        with self.events_path.open('r', encoding='utf-8') as handle:
            for index, raw in enumerate(line for line in handle if line.strip()):
                if index < cursor:
                    continue
                try:
                    payload = json.loads(raw)
                except json.JSONDecodeError:
                    continue
                if isinstance(payload, dict):
                    events.append(payload)
        return events

    def record_event(self, result: RunResult) -> None:
        payload = {
            'stage': result.stage,
            'index': result.index,
            'status': result.status,
            'cv': result.cv,
            'cv_rows': result.cv_rows,
            'steps_estimate': result.steps_estimate,
            'max_steps': result.max_steps,
            'velocity_seed': result.velocity_seed,
            'resampled_velocities': result.resampled_velocities,
            'wall_seconds': result.wall_seconds,
            'return_code': result.return_code,
            'workdir': str(result.workdir),
            'kept': result.kept,
        }
        self.record_json_event(payload)

    def keep_success(self, result: RunResult, interface_index: int, state_index: int) -> Path:
        restart = result.workdir / 'restart.xyz'
        if not restart.exists():
            raise FileNotFoundError(f'successful run did not write restart.xyz: {result.workdir}')
        state_path = self.state_dir(interface_index) / f'state_{state_index:06d}.xyz'
        shutil.copy2(restart, state_path)
        target = self.segment_dir(interface_index) / safe_name('segment', state_index)
        if target.exists():
            shutil.rmtree(target)
        shutil.copytree(result.workdir, target)
        return state_path

    def discard_failure(self, result: RunResult) -> None:
        if self.dry_run:
            return
        if self.config.keep_failed:
            result.kept = True
            self.record_event(result)
            return
        if result.workdir.exists():
            shutil.rmtree(result.workdir)
        result.kept = False
        self.record_event(result)

    def interval_width(self, interface_index: int) -> float:
        return abs(self.config.interfaces[interface_index + 1] - self.config.interfaces[interface_index])

    def can_refine_interface(self, interface_index: int, stats: dict[str, Any]) -> bool:
        if not self.config.adaptive_enabled:
            return False
        if self.config.adaptive_strategy != 'midpoint':
            raise ValueError(f'unsupported adaptive.strategy: {self.config.adaptive_strategy}')
        if len(self.adaptive_refinements) >= self.config.adaptive_max_refinements:
            return False
        if stats.get('successes', 0) != 0:
            return False
        if stats.get('trials', 0) <= 0:
            return False
        return self.interval_width(interface_index) > self.config.adaptive_min_interval_width

    def refine_interface(self, interface_index: int, stats: dict[str, Any]) -> None:
        left = self.config.interfaces[interface_index]
        right = self.config.interfaces[interface_index + 1]
        inserted = 0.5 * (left + right)
        old_step_limit = self.config.interface_max_steps[interface_index]
        self.config.interfaces.insert(interface_index + 1, inserted)
        self.config.interface_max_steps[interface_index:interface_index + 1] = [old_step_limit, old_step_limit]
        payload = {
            'event': 'adaptive_refine',
            'interface_index': interface_index,
            'from': left,
            'inserted': inserted,
            'to': right,
            'old_width': abs(right - left),
            'new_width': abs(inserted - left),
            'failed_trials': stats.get('trials', 0),
            'failed_successes': stats.get('successes', 0),
            'step_limit': old_step_limit,
            'interfaces': self.config.interfaces,
        }
        self.adaptive_refinements.append(payload)
        self.record_json_event(payload)

    def write_driver_state(
        self,
        phase: str,
        interface_index: int,
        state_pools: list[list[Path]],
        interface_stats: list[dict[str, Any]],
        flux_stats: dict[str, Any] | None,
        recovery_rounds: dict[int, int],
    ) -> None:
        payload = {
            'phase': phase,
            'interface_index': interface_index,
            'interfaces': self.config.interfaces,
            'interface_max_steps': self.config.interface_max_steps,
            'state_pools': [[str(path) for path in pool] for pool in state_pools],
            'interface_stats': interface_stats,
            'flux_stats': flux_stats,
            'adaptive_refinements': self.adaptive_refinements,
            'recovery_rounds': {str(key): value for key, value in recovery_rounds.items()},
            'stage_launch_counts': self.stage_launch_counts,
            'initial_model_cursor': self.initial_model_cursor,
            'event_cursor': self.count_event_lines(),
            'updated_at': time.strftime('%Y-%m-%dT%H:%M:%S%z'),
        }
        self.state_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')

    def load_driver_state(self) -> tuple[int, list[list[Path]], list[dict[str, Any]], dict[str, Any], dict[int, int]]:
        payload = json.loads(self.state_path.read_text(encoding='utf-8'))
        self.config.interfaces = [float(value) for value in payload['interfaces']]
        self.config.interface_max_steps = [int(value) for value in payload['interface_max_steps']]
        self.adaptive_refinements = payload.get('adaptive_refinements', [])
        self.stage_launch_counts = {str(key): int(value) for key, value in payload.get('stage_launch_counts', {}).items()}
        self.initial_model_cursor = int(payload.get('initial_model_cursor', 0))
        self.resume_phase = str(payload.get('phase', 'interfaces'))
        interface_index = int(payload.get('interface_index', 0))
        state_pools = [[Path(item) for item in pool] for pool in payload.get('state_pools', [])]
        interface_stats = list(payload.get('interface_stats', []))
        flux_stats = payload.get('flux_stats')
        if flux_stats is None:
            raise RuntimeError(f'state file has no flux_stats: {self.state_path}')
        recovery_rounds = {int(key): int(value) for key, value in payload.get('recovery_rounds', {}).items()}
        event_cursor = int(payload.get('event_cursor', self.count_event_lines()))
        reconciliation = self.reconcile_resume_state(event_cursor, interface_index, state_pools, interface_stats, flux_stats)
        resume_payload = {
            'event': 'resume',
            'state_file': str(self.state_path),
            'interface_index': interface_index,
            'resume_phase': self.resume_phase,
            'reconciliation': reconciliation,
        }
        self.record_json_event(resume_payload)
        if reconciliation['changed']:
            self.write_driver_state(self.resume_phase or 'interfaces', interface_index, state_pools, interface_stats, flux_stats, recovery_rounds)
        return interface_index, state_pools, interface_stats, flux_stats, recovery_rounds

    def ensure_state_pool(self, state_pools: list[list[Path]], interface_index: int) -> None:
        while len(state_pools) <= interface_index:
            state_pools.append([])

    def interface_stats_complete(self, stats: dict[str, Any]) -> bool:
        return (
            stats.get('trials', 0) >= self.config.min_trials_per_interface
            and stats.get('successes', 0) >= self.config.min_successes_per_interface
        )

    def upsert_interface_stats(
        self,
        interface_index: int,
        interface_stats: list[dict[str, Any]],
        stats: dict[str, Any],
    ) -> dict[str, Any]:
        stats['complete'] = self.interface_stats_complete(stats)
        if interface_index == len(interface_stats):
            interface_stats.append(stats)
            return stats
        if interface_index < len(interface_stats):
            self.merge_interface_stats(interface_stats[interface_index], stats)
            return interface_stats[interface_index]
        raise RuntimeError(f'interface stats are missing earlier layers before {interface_index}')

    def merged_interface_stats_copy(self, base: dict[str, Any] | None, extra: dict[str, Any]) -> dict[str, Any]:
        if base is None:
            merged = dict(extra)
        else:
            merged = dict(base)
            merged['trials'] = merged.get('trials', 0) + extra.get('trials', 0)
            merged['successes'] = merged.get('successes', 0) + extra.get('successes', 0)
            merged['failures'] = merged.get('failures', 0) + extra.get('failures', 0)
            merged['probability'] = merged['successes'] / merged['trials'] if merged['trials'] else 0.0
        merged['complete'] = self.interface_stats_complete(merged)
        return merged

    def empty_flux_stats(self) -> dict[str, Any]:
        return {
            'attempts': 0,
            'crossings': 0,
            'steps_estimate': 0,
            'time_ps_estimate': 0.0,
            'flux_per_ps': 0.0,
        }

    def merged_flux_stats_copy(self, base: dict[str, Any], extra: dict[str, Any]) -> dict[str, Any]:
        merged = dict(base)
        self.merge_flux_stats(merged, extra)
        return merged

    def empty_interface_delta(self, interface_index: int) -> dict[str, Any]:
        return {
            'interface_index': interface_index,
            'from': self.config.interfaces[interface_index],
            'to': self.config.interfaces[interface_index + 1],
            'trials': 0,
            'successes': 0,
            'failures': 0,
            'probability': 0.0,
            'complete': False,
        }

    def stage_interface_index(self, stage: Any) -> int | None:
        if not isinstance(stage, str) or not stage.startswith('interface_'):
            return None
        try:
            return int(stage.rsplit('_', 1)[1])
        except ValueError:
            return None

    def normalized_path_key(self, path: Path) -> str:
        return str(path.resolve())

    def next_unsynced_state(self, state_pools: list[list[Path]], interface_index: int) -> Path | None:
        self.ensure_state_pool(state_pools, interface_index)
        known = {self.normalized_path_key(path) for path in state_pools[interface_index]}
        for candidate in sorted(self.state_dir(interface_index).glob('state_*.xyz')):
            if self.normalized_path_key(candidate) not in known:
                return candidate
        return None

    def state_index_from_path(self, state_path: Path) -> int | None:
        match = re.search(r'state_(\d+)\.xyz$', state_path.name)
        return int(match.group(1)) if match else None

    def estimate_steps_from_segment(self, interface_index: int, state_path: Path) -> int:
        state_index = self.state_index_from_path(state_path)
        if state_index is None:
            return 0
        output = self.segment_dir(interface_index) / safe_name('segment', state_index) / 'gpu_sampling.out'
        if not output.exists():
            return 0
        return parse_completed_steps(output.read_text(encoding='utf-8', errors='replace'))

    def apply_interface_delta(
        self,
        interface_index: int,
        interface_stats: list[dict[str, Any]],
        delta: dict[str, Any],
    ) -> dict[str, Any]:
        if delta.get('trials', 0) <= 0:
            if interface_index < len(interface_stats):
                return interface_stats[interface_index]
            return delta
        if interface_index == len(interface_stats):
            delta['probability'] = delta['successes'] / delta['trials'] if delta['trials'] else 0.0
            delta['complete'] = self.interface_stats_complete(delta)
            interface_stats.append(delta)
            return delta
        if interface_index < len(interface_stats):
            self.merge_interface_stats(interface_stats[interface_index], delta)
            return interface_stats[interface_index]
        raise RuntimeError(f'interface stats are missing earlier layers before {interface_index}')

    def max_launch_index_from_event(self, payload: dict[str, Any]) -> tuple[str, int] | None:
        stage = payload.get('stage')
        if not isinstance(stage, str):
            return None
        workdir = payload.get('workdir')
        if isinstance(workdir, str):
            match = re.search(r'run_(\d+)$', workdir)
            if match:
                return stage, int(match.group(1))
        index = payload.get('index')
        if isinstance(index, int):
            return stage, index
        return None

    def reconcile_resume_state(
        self,
        event_cursor: int,
        interface_index: int,
        state_pools: list[list[Path]],
        interface_stats: list[dict[str, Any]],
        flux_stats: dict[str, Any],
    ) -> dict[str, Any]:
        deltas: dict[int, dict[str, Any]] = {}
        flux_delta = self.empty_flux_stats()
        used_state_files: set[str] = set()
        skipped: list[dict[str, Any]] = []
        events = self.read_event_lines_after(event_cursor)
        for payload in events:
            launch = self.max_launch_index_from_event(payload)
            if launch is not None:
                stage, launch_index = launch
                self.stage_launch_counts[stage] = max(self.stage_launch_counts.get(stage, 0), launch_index)
            stage = payload.get('stage')
            status = int(payload.get('status', 0))
            steps = int(payload.get('steps_estimate', 0) or 0)
            if stage == 'flux':
                if status > 0:
                    state = self.next_unsynced_state(state_pools, 0)
                    if state is None:
                        skipped.append({'stage': stage, 'reason': 'flux success event has no saved state file'})
                        continue
                    state_pools[0].append(state)
                    used_state_files.add(str(state))
                    flux_delta['attempts'] += 1
                    flux_delta['crossings'] += 1
                    flux_delta['steps_estimate'] += steps
                else:
                    flux_delta['attempts'] += 1
                    flux_delta['steps_estimate'] += steps
                continue
            stage_index = self.stage_interface_index(stage)
            if stage_index is None or stage_index >= len(self.config.interfaces) - 1:
                continue
            if stage_index not in deltas:
                deltas[stage_index] = self.empty_interface_delta(stage_index)
            if status > 0:
                state = self.next_unsynced_state(state_pools, stage_index + 1)
                if state is None:
                    skipped.append({'stage': stage, 'reason': 'success event has no saved state file'})
                    continue
                state_pools[stage_index + 1].append(state)
                used_state_files.add(str(state))
                deltas[stage_index]['trials'] += 1
                deltas[stage_index]['successes'] += 1
            else:
                deltas[stage_index]['trials'] += 1
                deltas[stage_index]['failures'] += 1

        file_successes = 0
        flux_file_successes = 0
        if self.resume_phase == 'flux':
            self.ensure_state_pool(state_pools, 0)
            while True:
                state = self.next_unsynced_state(state_pools, 0)
                if state is None or str(state) in used_state_files:
                    break
                state_pools[0].append(state)
                used_state_files.add(str(state))
                flux_delta['attempts'] += 1
                flux_delta['crossings'] += 1
                flux_delta['steps_estimate'] += self.estimate_steps_from_segment(0, state)
                flux_file_successes += 1
        if self.resume_phase == 'running' and 0 <= interface_index < len(self.config.interfaces) - 1:
            self.ensure_state_pool(state_pools, interface_index + 1)
            while True:
                state = self.next_unsynced_state(state_pools, interface_index + 1)
                if state is None or str(state) in used_state_files:
                    break
                if interface_index not in deltas:
                    deltas[interface_index] = self.empty_interface_delta(interface_index)
                state_pools[interface_index + 1].append(state)
                used_state_files.add(str(state))
                deltas[interface_index]['trials'] += 1
                deltas[interface_index]['successes'] += 1
                file_successes += 1

        if flux_delta['attempts']:
            flux_delta['time_ps_estimate'] = flux_delta['steps_estimate'] * self.config.timestep_fs / 1000.0
            flux_delta['flux_per_ps'] = (
                flux_delta['crossings'] / flux_delta['time_ps_estimate']
                if flux_delta['time_ps_estimate'] > 0
                else 0.0
            )
            self.merge_flux_stats(flux_stats, flux_delta)

        applied: list[dict[str, Any]] = []
        for index in sorted(deltas):
            delta = deltas[index]
            if delta.get('trials', 0) <= 0:
                continue
            delta['probability'] = delta['successes'] / delta['trials'] if delta['trials'] else 0.0
            delta['complete'] = self.interface_stats_complete(delta)
            merged = self.apply_interface_delta(index, interface_stats, delta)
            applied.append({
                'interface_index': index,
                'trials': delta['trials'],
                'successes': delta['successes'],
                'failures': delta['failures'],
                'merged_trials': merged.get('trials', 0),
                'merged_successes': merged.get('successes', 0),
            })
        return {
            'changed': bool(applied or skipped or file_successes or flux_delta['attempts'] or flux_file_successes),
            'event_cursor': event_cursor,
            'events_seen': len(events),
            'applied': applied,
            'flux_delta': flux_delta,
            'file_successes': file_successes,
            'flux_file_successes': flux_file_successes,
            'skipped': skipped,
        }

    def run_flux_stage(
        self,
        target_crossings: int | None = None,
        max_runs: int | None = None,
        state_offset: int = 0,
        progress_callback: Any = None,
    ) -> tuple[list[Path], dict[str, Any]]:
        target_crossings = self.config.flux_min_crossings if target_crossings is None else target_crossings
        max_runs = self.config.flux_max_runs if max_runs is None else max_runs
        crossings: list[Path] = []
        attempts = 0
        total_steps = 0

        def current_flux_stats() -> dict[str, Any]:
            total_time_ps = total_steps * self.config.timestep_fs / 1000.0
            return {
                'attempts': attempts,
                'crossings': len(crossings),
                'steps_estimate': total_steps,
                'time_ps_estimate': total_time_ps,
                'flux_per_ps': len(crossings) / total_time_ps if total_time_ps > 0 else 0.0,
            }

        while attempts < max_runs and len(crossings) < target_crossings:
            attempts += 1
            result = self.launch(
                'flux',
                attempts,
                self.next_initial_model(),
                self.config.interfaces[0],
                False,
                self.config.flux_max_steps,
            )
            self.results.append(result)
            total_steps += result.steps_estimate
            if result.return_code != 0:
                raise RuntimeError(f'gpu-sampling failed during flux run {attempts}: {result.workdir}')
            if result.status > 0:
                state = self.keep_success(result, 0, state_offset + len(crossings))
                crossings.append(state)
                self.record_event(result)
            else:
                self.discard_failure(result)
            if progress_callback is not None:
                progress_callback(crossings, current_flux_stats())
        if len(crossings) < target_crossings:
            raise RuntimeError('flux stage did not collect enough first-interface crossings')
        return crossings, current_flux_stats()

    def run_interface_stage(
        self,
        interface_index: int,
        starts: list[Path],
        allow_incomplete: bool = False,
        min_trials: int | None = None,
        max_trials: int | None = None,
        min_successes: int | None = None,
        max_successes: int | None = None,
        state_offset: int = 0,
        progress_callback: Any = None,
    ) -> tuple[list[Path], dict[str, Any]]:
        if not starts:
            raise RuntimeError(f'interface {interface_index} has no starting states')
        min_trials = self.config.min_trials_per_interface if min_trials is None else min_trials
        max_trials = self.config.max_trials_per_interface if max_trials is None else max_trials
        min_successes = self.config.min_successes_per_interface if min_successes is None else min_successes
        max_successes = self.config.max_successes_per_interface if max_successes is None else max_successes
        successes: list[Path] = []
        trials = 0
        failures = 0
        target = self.config.interfaces[interface_index + 1]
        start_cursor = 0

        def current_stats() -> dict[str, Any]:
            complete = trials >= min_trials and len(successes) >= min_successes
            probability = len(successes) / trials if trials else 0.0
            return {
                'interface_index': interface_index,
                'from': self.config.interfaces[interface_index],
                'to': self.config.interfaces[interface_index + 1],
                'trials': trials,
                'successes': len(successes),
                'failures': failures,
                'probability': probability,
                'complete': complete,
            }

        while trials < max_trials:
            if trials >= min_trials and len(successes) >= min_successes:
                break
            if len(successes) >= max_successes:
                break
            start_state = starts[start_cursor % len(starts)]
            start_cursor += 1
            for _ in range(self.config.replicas_per_crossing):
                if trials >= max_trials:
                    break
                if len(successes) >= max_successes:
                    break
                trials += 1
                stage = f'interface_{interface_index:03d}'
                result = self.launch(
                    stage,
                    trials,
                    start_state,
                    target,
                    True,
                    self.config.interface_max_steps[interface_index],
                )
                self.results.append(result)
                if result.return_code != 0:
                    raise RuntimeError(f'gpu-sampling failed during {stage} trial {trials}: {result.workdir}')
                if result.status > 0:
                    state = self.keep_success(result, interface_index + 1, state_offset + len(successes))
                    successes.append(state)
                    self.record_event(result)
                else:
                    failures += 1
                    self.discard_failure(result)
                if progress_callback is not None:
                    progress_callback(successes, current_stats())
            if trials >= min_trials and len(successes) >= min_successes:
                break
        stats = current_stats()
        complete = stats['complete']
        if not complete and not allow_incomplete:
            raise RuntimeError(f'interface {interface_index} did not meet min_trials and min_successes')
        return successes, stats

    def merge_interface_stats(self, base: dict[str, Any], extra: dict[str, Any]) -> None:
        base['trials'] += extra.get('trials', 0)
        base['successes'] += extra.get('successes', 0)
        base['failures'] += extra.get('failures', 0)
        base['probability'] = base['successes'] / base['trials'] if base['trials'] else 0.0
        base['complete'] = self.interface_stats_complete(base)

    def merge_flux_stats(self, base: dict[str, Any], extra: dict[str, Any]) -> None:
        base['attempts'] += extra.get('attempts', 0)
        base['crossings'] += extra.get('crossings', 0)
        base['steps_estimate'] += extra.get('steps_estimate', 0)
        base['time_ps_estimate'] += extra.get('time_ps_estimate', 0.0)
        time_ps = base['time_ps_estimate']
        base['flux_per_ps'] = base['crossings'] / time_ps if time_ps > 0 else 0.0

    def record_recovery_event(self, payload: dict[str, Any]) -> None:
        payload = {'event': 'recovery', **payload}
        self.record_json_event(payload)

    def refill_from_previous_interface(
        self,
        interface_index: int,
        state_pools: list[list[Path]],
        interface_stats: list[dict[str, Any]],
        flux_stats: dict[str, Any],
    ) -> bool:
        if not self.config.resample_velocities:
            self.record_recovery_event({
                'mode': 'previous_interface',
                'interface_index': interface_index,
                'status': 'skipped',
                'reason': 'resample_velocities is false; deterministic relaunches would duplicate trajectories',
            })
            return False
        if interface_index == 0:
            crossings, extra_flux = self.run_flux_stage(
                target_crossings=self.config.recovery_refill_successes,
                max_runs=self.config.recovery_refill_max_trials,
                state_offset=len(state_pools[0]),
            )
            self.merge_flux_stats(flux_stats, extra_flux)
            state_pools[0].extend(crossings)
            self.record_recovery_event({
                'mode': 'previous_interface',
                'interface_index': interface_index,
                'status': 'refilled_flux',
                'new_states': len(crossings),
            })
            return bool(crossings)
        previous_index = interface_index - 1
        self.ensure_state_pool(state_pools, interface_index)
        new_states, stats = self.run_interface_stage(
            previous_index,
            state_pools[previous_index],
            allow_incomplete=True,
            state_offset=len(state_pools[interface_index]),
            min_trials=1,
            max_trials=self.config.recovery_refill_max_trials,
            min_successes=self.config.recovery_refill_successes,
            max_successes=self.config.recovery_refill_successes,
        )
        if previous_index < len(interface_stats):
            self.merge_interface_stats(interface_stats[previous_index], stats)
        state_pools[interface_index].extend(new_states)
        self.record_recovery_event({
            'mode': 'previous_interface',
            'interface_index': interface_index,
            'source_interface_index': previous_index,
            'status': 'refilled' if new_states else 'failed',
            'new_states': len(new_states),
            'trials': stats['trials'],
            'successes': stats['successes'],
        })
        return bool(new_states)

    def refill_from_initial_state(
        self,
        interface_index: int,
        state_pools: list[list[Path]],
        interface_stats: list[dict[str, Any]],
        flux_stats: dict[str, Any],
    ) -> bool:
        crossings, extra_flux = self.run_flux_stage(
            target_crossings=self.config.recovery_refill_successes,
            max_runs=self.config.recovery_refill_max_trials,
            state_offset=len(state_pools[0]),
        )
        self.merge_flux_stats(flux_stats, extra_flux)
        state_pools[0].extend(crossings)
        starts = crossings
        for upstream in range(interface_index):
            if not starts:
                break
            self.ensure_state_pool(state_pools, upstream + 1)
            starts, stats = self.run_interface_stage(
                upstream,
                starts,
                allow_incomplete=True,
                state_offset=len(state_pools[upstream + 1]),
                min_trials=1,
                max_trials=self.config.recovery_refill_max_trials,
                min_successes=self.config.recovery_refill_successes,
                max_successes=self.config.recovery_refill_successes,
            )
            if upstream < len(interface_stats):
                self.merge_interface_stats(interface_stats[upstream], stats)
            state_pools[upstream + 1].extend(starts)
        self.record_recovery_event({
            'mode': 'initial_state',
            'interface_index': interface_index,
            'status': 'refilled' if starts else 'failed',
            'new_states': len(starts),
        })
        return bool(starts)

    def recover_failed_interface(
        self,
        interface_index: int,
        state_pools: list[list[Path]],
        interface_stats: list[dict[str, Any]],
        flux_stats: dict[str, Any],
        recovery_rounds: dict[int, int],
    ) -> bool:
        if self.config.recovery_mode == 'stop':
            return False
        used = recovery_rounds.get(interface_index, 0)
        if used >= self.config.recovery_max_rounds_per_interface:
            self.record_recovery_event({
                'mode': self.config.recovery_mode,
                'interface_index': interface_index,
                'status': 'skipped',
                'reason': 'max_rounds_per_interface reached',
            })
            return False
        recovery_rounds[interface_index] = used + 1
        if self.config.recovery_mode == 'previous_interface':
            return self.refill_from_previous_interface(interface_index, state_pools, interface_stats, flux_stats)
        if self.config.recovery_mode == 'initial_state':
            return self.refill_from_initial_state(interface_index, state_pools, interface_stats, flux_stats)
        return False

    def write_summary(self, flux: dict[str, Any], interfaces: list[dict[str, Any]]) -> dict[str, Any]:
        product_probability = 1.0
        for item in interfaces:
            product_probability *= item['probability']
        rate_per_ps = flux['flux_per_ps'] * product_probability
        barrier_kbt = None if product_probability <= 0 else -math.log(product_probability)
        barrier_ev = None
        if barrier_kbt is not None and self.config.temperature_K is not None:
            barrier_ev = barrier_kbt * KB_EV_PER_K * self.config.temperature_K
        summary = {
            'interfaces': self.config.interfaces,
            'direction': self.config.direction,
            'cv_index': self.config.cv_index,
            'flux': flux,
            'conditional_probabilities': interfaces,
            'product_probability': product_probability,
            'rate_per_ps': rate_per_ps,
            'barrier_kBT_from_probability_product': barrier_kbt,
            'barrier_eV_from_probability_product': barrier_ev,
            'run_step_limits': {
                'flux_max_steps': self.config.flux_max_steps,
                'interface_max_steps': self.config.interface_max_steps,
            },
            'resample_velocities': self.config.resample_velocities,
            'overwrite_work_dir': self.config.overwrite_work_dir,
            'resume': self.config.resume,
            'state_file': str(self.state_path),
            'recovery': {
                'mode': self.config.recovery_mode,
                'max_rounds_per_interface': self.config.recovery_max_rounds_per_interface,
                'refill_successes': self.config.recovery_refill_successes,
                'refill_max_trials': self.config.recovery_refill_max_trials,
            },
            'adaptive': {
                'enabled': self.config.adaptive_enabled,
                'min_interval_width': self.config.adaptive_min_interval_width,
                'max_refinements': self.config.adaptive_max_refinements,
                'strategy': self.config.adaptive_strategy,
                'refinements': self.adaptive_refinements,
            },
            'time_estimate_note': 'steps are parsed from gpu_sampling.out when possible; otherwise they fall back to GASCVlog rows times cv_log_interval',
        }
        (self.config.work_dir / 'summary.json').write_text(json.dumps(summary, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
        with (self.config.work_dir / 'interfaces.csv').open('w', encoding='utf-8', newline='') as handle:
            writer = csv.DictWriter(handle, fieldnames=['interface_index', 'from', 'to', 'trials', 'successes', 'failures', 'probability', 'complete'])
            writer.writeheader()
            for item in interfaces:
                writer.writerow(item)
        return summary

    def run(self) -> dict[str, Any]:
        self.prepare()
        if self.dry_run:
            example = self.launch(
                'dry_flux',
                1,
                self.next_initial_model(),
                self.config.interfaces[0],
                False,
                self.config.flux_max_steps,
            )
            return {
                'dry_run': True,
                'example_workdir': str(example.workdir),
                'message': 'prepared one gpu-sampling FFS task directory without launching MD',
            }
        if self.config.resume:
            interface_index, state_pools, interface_stats, flux_stats, recovery_rounds = self.load_driver_state()
            if self.resume_phase == 'flux':
                self.ensure_state_pool(state_pools, 0)
                needed_crossings = max(0, self.config.flux_min_crossings - int(flux_stats.get('crossings', 0)))
                remaining_runs = max(0, self.config.flux_max_runs - int(flux_stats.get('attempts', 0)))

                def write_flux_progress(partial_crossings: list[Path], partial_stats: dict[str, Any]) -> None:
                    progress_pools = [list(pool) for pool in state_pools]
                    self.ensure_state_pool(progress_pools, 0)
                    progress_pools[0].extend(partial_crossings)
                    progress_flux = self.merged_flux_stats_copy(flux_stats, partial_stats)
                    self.write_driver_state('flux', 0, progress_pools, interface_stats, progress_flux, recovery_rounds)

                extra_crossings, extra_flux = self.run_flux_stage(
                    target_crossings=needed_crossings,
                    max_runs=remaining_runs,
                    state_offset=len(state_pools[0]),
                    progress_callback=write_flux_progress,
                )
                self.merge_flux_stats(flux_stats, extra_flux)
                state_pools[0].extend(extra_crossings)
                interface_index = 0
                self.resume_phase = None
                self.write_driver_state('interfaces', interface_index, state_pools, interface_stats, flux_stats, recovery_rounds)
        else:
            state_pools = [[]]
            interface_stats = []
            recovery_rounds = {}
            flux_stats = self.empty_flux_stats()
            interface_index = 0

            def write_flux_progress(partial_crossings: list[Path], partial_stats: dict[str, Any]) -> None:
                progress_pools = [list(pool) for pool in state_pools]
                progress_pools[0].extend(partial_crossings)
                progress_flux = self.merged_flux_stats_copy(flux_stats, partial_stats)
                self.write_driver_state('flux', interface_index, progress_pools, interface_stats, progress_flux, recovery_rounds)

            starts, extra_flux = self.run_flux_stage(progress_callback=write_flux_progress)
            self.merge_flux_stats(flux_stats, extra_flux)
            state_pools[0].extend(starts)
            self.write_driver_state('interfaces', interface_index, state_pools, interface_stats, flux_stats, recovery_rounds)
        while interface_index < len(self.config.interfaces) - 1:
            self.ensure_state_pool(state_pools, interface_index)
            self.ensure_state_pool(state_pools, interface_index + 1)
            starts = state_pools[interface_index]
            accumulated = interface_stats[interface_index] if interface_index < len(interface_stats) else None
            resuming_running_batch = self.resume_phase == 'running'
            if self.resume_phase == 'failed':
                self.resume_phase = None
                if self.recover_failed_interface(interface_index, state_pools, interface_stats, flux_stats, recovery_rounds):
                    self.write_driver_state('recovered', interface_index, state_pools, interface_stats, flux_stats, recovery_rounds)
                    continue
                self.write_driver_state('failed', interface_index, state_pools, interface_stats, flux_stats, recovery_rounds)
                raise RuntimeError(f'interface {interface_index} did not meet min_trials and min_successes')
            self.resume_phase = None
            if accumulated is not None and self.interface_stats_complete(accumulated):
                interface_index += 1
                self.write_driver_state('interfaces', interface_index, state_pools, interface_stats, flux_stats, recovery_rounds)
                continue

            remaining_min_trials = self.config.min_trials_per_interface
            remaining_min_successes = self.config.min_successes_per_interface
            remaining_max_successes = self.config.max_successes_per_interface
            remaining_max_trials = self.config.max_trials_per_interface
            if accumulated is not None:
                remaining_min_trials = max(0, self.config.min_trials_per_interface - accumulated.get('trials', 0))
                remaining_min_successes = max(0, self.config.min_successes_per_interface - accumulated.get('successes', 0))
                remaining_max_successes = max(0, self.config.max_successes_per_interface - accumulated.get('successes', 0))
                if resuming_running_batch and self.config.max_trials_per_interface > 0:
                    used_in_batch = accumulated.get('trials', 0) % self.config.max_trials_per_interface
                    if used_in_batch:
                        remaining_max_trials = max(0, self.config.max_trials_per_interface - used_in_batch)
                    elif accumulated.get('trials', 0) > 0:
                        remaining_max_trials = 0

            def write_interface_progress(partial_starts: list[Path], partial_stats: dict[str, Any]) -> None:
                progress_pools = [list(pool) for pool in state_pools]
                progress_pools[interface_index + 1].extend(partial_starts)
                progress_stats = [dict(item) for item in interface_stats]
                merged_stats = self.merged_interface_stats_copy(accumulated, partial_stats)
                if interface_index < len(progress_stats):
                    progress_stats[interface_index] = merged_stats
                elif interface_index == len(progress_stats):
                    progress_stats.append(merged_stats)
                else:
                    raise RuntimeError(f'interface stats are missing earlier layers before {interface_index}')
                self.write_driver_state('running', interface_index, progress_pools, progress_stats, flux_stats, recovery_rounds)

            candidate_starts, stats = self.run_interface_stage(
                interface_index,
                starts,
                allow_incomplete=True,
                min_trials=remaining_min_trials,
                max_trials=remaining_max_trials,
                min_successes=remaining_min_successes,
                max_successes=remaining_max_successes,
                state_offset=len(state_pools[interface_index + 1]),
                progress_callback=write_interface_progress,
            )
            if self.can_refine_interface(interface_index, stats):
                self.refine_interface(interface_index, stats)
                self.write_driver_state('adaptive_refine', interface_index, state_pools, interface_stats, flux_stats, recovery_rounds)
                continue

            state_pools[interface_index + 1].extend(candidate_starts)
            accumulated_stats = self.upsert_interface_stats(interface_index, interface_stats, stats)
            if self.interface_stats_complete(accumulated_stats):
                accumulated_stats['complete'] = True
                interface_index += 1
                self.write_driver_state('interfaces', interface_index, state_pools, interface_stats, flux_stats, recovery_rounds)
                continue
            if self.recover_failed_interface(interface_index, state_pools, interface_stats, flux_stats, recovery_rounds):
                self.write_driver_state('recovered', interface_index, state_pools, interface_stats, flux_stats, recovery_rounds)
                continue
            self.write_driver_state('failed', interface_index, state_pools, interface_stats, flux_stats, recovery_rounds)
            raise RuntimeError(f'interface {interface_index} did not meet min_trials and min_successes')
        return self.write_summary(flux_stats, interface_stats)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description='Serial forward-flux-sampling driver for gpu-sampling')
    parser.add_argument('config', type=Path, help='FFS yaml configuration')
    parser.add_argument('--dry-run', action='store_true', help='prepare directories without launching gpu-sampling')
    args = parser.parse_args(argv)
    config = FFSConfig.from_yaml(args.config.resolve())
    driver = FFSDriver(config, dry_run=args.dry_run)
    summary = driver.run()
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
